### ISSUE TITLE
not able to delete an item

### ISSUE THREAD

**Issue by grawk** [krakenjs/kraken-example-with-shoppingcart#9]
when clicking "Delete" on an item to remove it from the Product model, the `delete` method of the Product router is not engaged.

In the form there is a hidden field:

``` html
<input type="hidden" name="_method" value="DELETE">
```

I'm not sure if this is supposed to trigger anything either via an express convention or otherwise, but the submission of the delete form just calls the post method.

**Comment by ulloa** [comment]
In order to activate the delete method on POST form you need the following in your server index.js:

```
var methodOverride = require('method-override'); //for DELETE and HTTP methods
var bodyParser     = require('body-parser'); //for middleware methodoverride
```

```
//Below is the parsing for HTTP requests not in HTML (PUT, DELETE)
app.use(bodyParser.json()); // get information from html forms
app.use(bodyParser.urlencoded({ extended: true }));


app.use(methodOverride(function(req, res){
  if (req.body && typeof req.body === 'object' && '_method' in req.body) {
    // look in urlencoded POST bodies and delete it
    var method = req.body._method
    delete req.body._method
    return method
  }
}))
```

I just noticed a closed issue( https://github.com/krakenjs/kraken-example-with-shoppingcart/issues/11 )that regarding method-override for delete. I too had trouble using the options for this. I just omitted options and put this outside of options. That probably also solved your problem.

**Comment by grawk** [comment]
resolved with the latest PR adding "react"
